### PR TITLE
Add "Vary: Accept" header when content negotiation was used.

### PR DESCRIPTION
**Pull request by melgi**
This patch adds the Vary header to the response in case content negotiation was used to select a representation.

```
$ curl -v -H 'Accept-Encoding: gzip' -H 'Accept: text/turtle' http://localhost:8080/test
...
> Host: localhost:8080
> User-Agent: curl/7.62.0
> Accept-Encoding: gzip
> Accept: text/turtle
>
< HTTP/1.1 200 OK
< access-control-allow-origin: *
< access-control-allow-headers: Origin, X-Requested-With, Content-Type, Accept, Range
< Vary: Accept
< content-type: text/turtle
< server: ecstatic-3.2.1
< Content-Encoding: gzip
...
```

Note that to be correct, the Vary header in this example should actually be 'Accept, Accept-Encoding', because a gzipped response was asked and returned, but this needs to be fixed in `node-ecstatic`.

I read your excellent [nginx-conneg article](https://pieterheyvaert.com/blog/2019/02/25/nginx-conneg/), maybe it would be good to add a section about the Vary header there (and the problems with it)?

### CODE REVIEW

**Comment by pheyvaer** [comment]
Hi @melgi 

Thanks for the PR! Could you add a corresponding test too?

**Comment by pheyvaer** [comment]
Hi @melgi 

Thanks for the update, looks great! Could you maybe add a sentence or two about the vary header to the conneg part of the README?

**Comment by melgi** [comment]
Hi, I updated the readme.
You can ignore the Dockerfile.

**Comment by pheyvaer** [comment]
Thanks! Did you run the test via `npm test`? Because I'm getting 15 errors.

**Comment by pheyvaer** [comment]
Ok. great! Regarding the docker file, you said to ignore it. So can you remove it from the PR?

**Pull request closed without merging**
